 FROM chuanwen/cowsay:latest
#  WORKDIR /usr/games/

#  RUN cowsay
#  RUN dragon-and-cow

#  ENTRYPOINT ["cowsay", "-f", "VQV TRYBE"]
#  CMD [ "Muuuuuuhhh" ]
ENTRYPOINT [ "/usr/games/cowsay" ]
# CMD [ "VQV TRYBE" ]
# CMD [ "-f", "koala", "VQV TRYBE"]
CMD [ "VQV TRYBE"]

# ENTRYPOINT ["/usr/games/cowsay","-f","docker"]
# CMD ["moby","dock"]