version: "3"

services:
  ghost:
    image: ghost:1-alpine
    restart: always
    ports:
      - 2368:2368
    depends_on:
      - "db"
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: filipe12
      database__connection__database: ghost
    networks:
      - my-network
  db:
    platform: linux/x86_64
    image: mysql:5.7.40
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: filipe12 
    volumes:
      - ./dados-do-banco:/var/lib/mysql
    networks:
      - my-network
  
volumes:
  dado-do-banco:

networks:
  my-network:
